const angka = {

id:"angka",

nama:"Angka",

data:[

{jp:"いち",romaji:"Ichi",arti:"Satu"},
{jp:"に",romaji:"Ni",arti:"Dua"},
{jp:"さん",romaji:"San",arti:"Tiga"},
{jp:"よん",romaji:"Yon",arti:"Empat"},
{jp:"ご",romaji:"Go",arti:"Lima"},
{jp:"ろく",romaji:"Roku",arti:"Enam"},
{jp:"なな",romaji:"Nana",arti:"Tujuh"},
{jp:"はち",romaji:"Hachi",arti:"Delapan"},
{jp:"きゅう",romaji:"Kyuu",arti:"Sembilan"},
{jp:"じゅう",romaji:"Juu",arti:"Sepuluh"},

{jp:"じゅういち",romaji:"Juuichi",arti:"Sebelas"},
{jp:"じゅうに",romaji:"Juuni",arti:"Dua Belas"},
{jp:"じゅうさん",romaji:"Juusan",arti:"Tiga Belas"},
{jp:"じゅうよん",romaji:"Juuyon",arti:"Empat Belas"},
{jp:"じゅうご",romaji:"Juugo",arti:"Lima Belas"},
{jp:"じゅうろく",romaji:"Juuroku",arti:"Enam Belas"},
{jp:"じゅうなな",romaji:"Juunana",arti:"Tujuh Belas"},
{jp:"じゅうはち",romaji:"Juuhachi",arti:"Delapan Belas"},
{jp:"じゅうきゅう",romaji:"Juukyuu",arti:"Sembilan Belas"},
{jp:"にじゅう",romaji:"Nijuu",arti:"Dua Puluh"},

{jp:"にじゅういち",romaji:"Nijuuichi",arti:"Dua Puluh Satu"},
{jp:"にじゅうに",romaji:"Nijuuni",arti:"Dua Puluh Dua"},
{jp:"にじゅうさん",romaji:"Nijuusan",arti:"Dua Puluh Tiga"},
{jp:"にじゅうよん",romaji:"Nijuuyon",arti:"Dua Puluh Empat"},
{jp:"にじゅうご",romaji:"Nijuugo",arti:"Dua Puluh Lima"},
{jp:"にじゅうろく",romaji:"Nijuuroku",arti:"Dua Puluh Enam"},
{jp:"にじゅうなな",romaji:"Nijuunana",arti:"Dua Puluh Tujuh"},
{jp:"にじゅうはち",romaji:"Nijuuhachi",arti:"Dua Puluh Delapan"},
{jp:"にじゅうきゅう",romaji:"Nijuukyuu",arti:"Dua Puluh Sembilan"},
{jp:"さんじゅう",romaji:"Sanjuu",arti:"Tiga Puluh"},

{jp:"さんじゅういち",romaji:"Sanjuuichi",arti:"Tiga Puluh Satu"},
{jp:"さんじゅうに",romaji:"Sanjuuni",arti:"Tiga Puluh Dua"},
{jp:"さんじゅうさん",romaji:"Sanjuusan",arti:"Tiga Puluh Tiga"},
{jp:"さんじゅうよん",romaji:"Sanjuuyon",arti:"Tiga Puluh Empat"},
{jp:"さんじゅうご",romaji:"Sanjuugo",arti:"Tiga Puluh Lima"},
{jp:"さんじゅうろく",romaji:"Sanjuuroku",arti:"Tiga Puluh Enam"},
{jp:"さんじゅうなな",romaji:"Sanjuunana",arti:"Tiga Puluh Tujuh"},
{jp:"さんじゅうはち",romaji:"Sanjuuhachi",arti:"Tiga Puluh Delapan"},
{jp:"さんじゅうきゅう",romaji:"Sanjuukyuu",arti:"Tiga Puluh Sembilan"},
{jp:"よんじゅう",romaji:"Yonjuu",arti:"Empat Puluh"},

{jp:"よんじゅういち",romaji:"Yonjuuichi",arti:"Empat Puluh Satu"},
{jp:"よんじゅうに",romaji:"Yonjuuni",arti:"Empat Puluh Dua"},
{jp:"よんじゅうさん",romaji:"Yonjuusan",arti:"Empat Puluh Tiga"},
{jp:"よんじゅうよん",romaji:"Yonjuuyon",arti:"Empat Puluh Empat"},
{jp:"よんじゅうご",romaji:"Yonjuugo",arti:"Empat Puluh Lima"},
{jp:"よんじゅうろく",romaji:"Yonjuuroku",arti:"Empat Puluh Enam"},
{jp:"よんじゅうなな",romaji:"Yonjuunana",arti:"Empat Puluh Tujuh"},
{jp:"よんじゅうはち",romaji:"Yonjuuhachi",arti:"Empat Puluh Delapan"},
{jp:"よんじゅうきゅう",romaji:"Yonjuukyuu",arti:"Empat Puluh Sembilan"},
{jp:"ごじゅう",romaji:"Gojuu",arti:"Lima Puluh"}

,

{jp:"ごじゅういち",romaji:"Gojuuichi",arti:"Lima Puluh Satu"},
{jp:"ごじゅうに",romaji:"Gojuuni",arti:"Lima Puluh Dua"},
{jp:"ごじゅうさん",romaji:"Gojuusan",arti:"Lima Puluh Tiga"},
{jp:"ごじゅうよん",romaji:"Gojuuyon",arti:"Lima Puluh Empat"},
{jp:"ごじゅうご",romaji:"Gojuugo",arti:"Lima Puluh Lima"},
{jp:"ごじゅうろく",romaji:"Gojuuroku",arti:"Lima Puluh Enam"},
{jp:"ごじゅうなな",romaji:"Gojuunana",arti:"Lima Puluh Tujuh"},
{jp:"ごじゅうはち",romaji:"Gojuuhachi",arti:"Lima Puluh Delapan"},
{jp:"ごじゅうきゅう",romaji:"Gojuukyuu",arti:"Lima Puluh Sembilan"},
{jp:"ろくじゅう",romaji:"Rokujuu",arti:"Enam Puluh"},

{jp:"ろくじゅういち",romaji:"Rokujuuichi",arti:"Enam Puluh Satu"},
{jp:"ろくじゅうに",romaji:"Rokujuuni",arti:"Enam Puluh Dua"},
{jp:"ろくじゅうさん",romaji:"Rokujuusan",arti:"Enam Puluh Tiga"},
{jp:"ろくじゅうよん",romaji:"Rokujuuyon",arti:"Enam Puluh Empat"},
{jp:"ろくじゅうご",romaji:"Rokujuugo",arti:"Enam Puluh Lima"},
{jp:"ろくじゅうろく",romaji:"Rokujuuroku",arti:"Enam Puluh Enam"},
{jp:"ろくじゅうなな",romaji:"Rokujuunana",arti:"Enam Puluh Tujuh"},
{jp:"ろくじゅうはち",romaji:"Rokujuuhachi",arti:"Enam Puluh Delapan"},
{jp:"ろくじゅうきゅう",romaji:"Rokujuukyuu",arti:"Enam Puluh Sembilan"},
{jp:"ななじゅう",romaji:"Nanajuu",arti:"Tujuh Puluh"},

{jp:"ななじゅういち",romaji:"Nanajuuichi",arti:"Tujuh Puluh Satu"},
{jp:"ななじゅうに",romaji:"Nanajuuni",arti:"Tujuh Puluh Dua"},
{jp:"ななじゅうさん",romaji:"Nanajuusan",arti:"Tujuh Puluh Tiga"},
{jp:"ななじゅうよん",romaji:"Nanajuuyon",arti:"Tujuh Puluh Empat"},
{jp:"ななじゅうご",romaji:"Nanajuugo",arti:"Tujuh Puluh Lima"},
{jp:"ななじゅうろく",romaji:"Nanajuuroku",arti:"Tujuh Puluh Enam"},
{jp:"ななじゅうなな",romaji:"Nanajuunana",arti:"Tujuh Puluh Tujuh"},
{jp:"ななじゅうはち",romaji:"Nanajuuhachi",arti:"Tujuh Puluh Delapan"},
{jp:"ななじゅうきゅう",romaji:"Nanajuukyuu",arti:"Tujuh Puluh Sembilan"},
{jp:"はちじゅう",romaji:"Hachijuu",arti:"Delapan Puluh"},

{jp:"はちじゅういち",romaji:"Hachijuuichi",arti:"Delapan Puluh Satu"},
{jp:"はちじゅうに",romaji:"Hachijuuni",arti:"Delapan Puluh Dua"},
{jp:"はちじゅうさん",romaji:"Hachijuusan",arti:"Delapan Puluh Tiga"},
{jp:"はちじゅうよん",romaji:"Hachijuuyon",arti:"Delapan Puluh Empat"},
{jp:"はちじゅうご",romaji:"Hachijuugo",arti:"Delapan Puluh Lima"},
{jp:"はちじゅうろく",romaji:"Hachijuuroku",arti:"Delapan Puluh Enam"},
{jp:"はちじゅうなな",romaji:"Hachijuunana",arti:"Delapan Puluh Tujuh"},
{jp:"はちじゅうはち",romaji:"Hachijuuhachi",arti:"Delapan Puluh Delapan"},
{jp:"はちじゅうきゅう",romaji:"Hachijuukyuu",arti:"Delapan Puluh Sembilan"},
{jp:"きゅうじゅう",romaji:"Kyuujuu",arti:"Sembilan Puluh"},

{jp:"きゅうじゅういち",romaji:"Kyuujuuichi",arti:"Sembilan Puluh Satu"},
{jp:"きゅうじゅうに",romaji:"Kyuujuuni",arti:"Sembilan Puluh Dua"},
{jp:"きゅうじゅうさん",romaji:"Kyuujuusan",arti:"Sembilan Puluh Tiga"},
{jp:"きゅうじゅうよん",romaji:"Kyuujuuyon",arti:"Sembilan Puluh Empat"},
{jp:"きゅうじゅうご",romaji:"Kyuujuugo",arti:"Sembilan Puluh Lima"},
{jp:"きゅうじゅうろく",romaji:"Kyuujuuroku",arti:"Sembilan Puluh Enam"},
{jp:"きゅうじゅうなな",romaji:"Kyuujuunana",arti:"Sembilan Puluh Tujuh"},
{jp:"きゅうじゅうはち",romaji:"Kyuujuuhachi",arti:"Sembilan Puluh Delapan"},
{jp:"きゅうじゅうきゅう",romaji:"Kyuujuukyuu",arti:"Sembilan Puluh Sembilan"},
{jp:"ひゃく",romaji:"Hyaku",arti:"Seratus"}

]

};