const hewan = {

id:"hewan",

nama:"Hewan",

data:[

{jp:"どうぶつ",romaji:"Doubutsu",arti:"Hewan"},
{jp:"いぬ",romaji:"Inu",arti:"Anjing"},
{jp:"ねこ",romaji:"Neko",arti:"Kucing"},
{jp:"うさぎ",romaji:"Usagi",arti:"Kelinci"},
{jp:"ねずみ",romaji:"Nezumi",arti:"Tikus"},
{jp:"うま",romaji:"Uma",arti:"Kuda"},
{jp:"うし",romaji:"Ushi",arti:"Sapi"},
{jp:"ぶた",romaji:"Buta",arti:"Babi"},
{jp:"ひつじ",romaji:"Hitsuji",arti:"Domba"},
{jp:"やぎ",romaji:"Yagi",arti:"Kambing"},
{jp:"しか",romaji:"Shika",arti:"Rusa"},
{jp:"ぞう",romaji:"Zou",arti:"Gajah"},
{jp:"きりん",romaji:"Kirin",arti:"Jerapah"},
{jp:"らいおん",romaji:"Raion",arti:"Singa"},
{jp:"とら",romaji:"Tora",arti:"Harimau"},
{jp:"ひょう",romaji:"Hyou",arti:"Macan Tutul"},
{jp:"くま",romaji:"Kuma",arti:"Beruang"},
{jp:"ぱんだ",romaji:"Panda",arti:"Panda"},
{jp:"さる",romaji:"Saru",arti:"Monyet"},
{jp:"ごりら",romaji:"Gorira",arti:"Gorila"},
{jp:"おおかみ",romaji:"Ookami",arti:"Serigala"},
{jp:"きつね",romaji:"Kitsune",arti:"Rubah"},
{jp:"たぬき",romaji:"Tanuki",arti:"Anjing Rakun"},
{jp:"りす",romaji:"Risu",arti:"Tupai"},
{jp:"こうもり",romaji:"Koumori",arti:"Kelelawar"},
{jp:"らくだ",romaji:"Rakuda",arti:"Unta"},
{jp:"かば",romaji:"Kaba",arti:"Kuda Nil"},
{jp:"さい",romaji:"Sai",arti:"Badak"},
{jp:"わに",romaji:"Wani",arti:"Buaya"},
{jp:"へび",romaji:"Hebi",arti:"Ular"},
{jp:"とかげ",romaji:"Tokage",arti:"Kadal"},
{jp:"かめ",romaji:"Kame",arti:"Kura-kura"},
{jp:"かえる",romaji:"Kaeru",arti:"Katak"},
{jp:"にわとり",romaji:"Niwatori",arti:"Ayam"},
{jp:"ひよこ",romaji:"Hiyoko",arti:"Anak Ayam"},
{jp:"あひる",romaji:"Ahiru",arti:"Bebek"},
{jp:"がちょう",romaji:"Gachou",arti:"Angsa"},
{jp:"はと",romaji:"Hato",arti:"Merpati"},
{jp:"すずめ",romaji:"Suzume",arti:"Burung Pipit"},
{jp:"からす",romaji:"Karasu",arti:"Gagak"},
{jp:"わし",romaji:"Washi",arti:"Elang"},
{jp:"たか",romaji:"Taka",arti:"Rajawali"},
{jp:"ふくろう",romaji:"Fukurou",arti:"Burung Hantu"},
{jp:"くじゃく",romaji:"Kujaku",arti:"Merak"},
{jp:"おうむ",romaji:"Oumu",arti:"Burung Beo"},
{jp:"ペンギン",romaji:"Pengin",arti:"Pinguin"},
{jp:"だちょう",romaji:"Dachou",arti:"Burung Unta"},
{jp:"つばめ",romaji:"Tsubame",arti:"Burung Walet"},
{jp:"さかな",romaji:"Sakana",arti:"Ikan"},
{jp:"まぐろ",romaji:"Maguro",arti:"Ikan Tuna"},
{jp:"さけ",romaji:"Sake",arti:"Ikan Salmon"},
{jp:"たい",romaji:"Tai",arti:"Ikan Kakap"},
{jp:"こい",romaji:"Koi",arti:"Ikan Koi"},
{jp:"きんぎょ",romaji:"Kingyo",arti:"Ikan Mas"},
{jp:"いるか",romaji:"Iruka",arti:"Lumba-lumba"},
{jp:"くじら",romaji:"Kujira",arti:"Paus"},
{jp:"さめ",romaji:"Same",arti:"Hiu"},
{jp:"たこ",romaji:"Tako",arti:"Gurita"},
{jp:"いか",romaji:"Ika",arti:"Cumi-cumi"},
{jp:"えび",romaji:"Ebi",arti:"Udang"},
{jp:"かに",romaji:"Kani",arti:"Kepiting"},
{jp:"くらげ",romaji:"Kurage",arti:"Ubur-ubur"},
{jp:"ひとで",romaji:"Hitode",arti:"Bintang Laut"},
{jp:"あざらし",romaji:"Azarashi",arti:"Anjing Laut"},
{jp:"おっとせい",romaji:"Ottosei",arti:"Singa Laut"},
{jp:"かい",romaji:"Kai",arti:"Kerang"},
{jp:"むし",romaji:"Mushi",arti:"Serangga"},
{jp:"ちょう",romaji:"Chou",arti:"Kupu-kupu"},
{jp:"はち",romaji:"Hachi",arti:"Lebah"},
{jp:"あり",romaji:"Ari",arti:"Semut"},
{jp:"か",romaji:"Ka",arti:"Nyamuk"},
{jp:"はえ",romaji:"Hae",arti:"Lalat"},
{jp:"とんぼ",romaji:"Tonbo",arti:"Capung"},
{jp:"せみ",romaji:"Semi",arti:"Jangkrik"},
{jp:"かぶとむし",romaji:"Kabutomushi",arti:"Kumbang Tanduk"},
{jp:"てんとうむし",romaji:"Tentoumushi",arti:"Kepik"},
{jp:"くも",romaji:"Kumo",arti:"Laba-laba"},
{jp:"みみず",romaji:"Mimizu",arti:"Cacing"},
{jp:"かたつむり",romaji:"Katatsumuri",arti:"Siput"},
{jp:"なめくじ",romaji:"Namekuji",arti:"Siput Tanpa Cangkang"},
{jp:"パンダ",romaji:"Panda",arti:"Panda"},
{jp:"コアラ",romaji:"Koara",arti:"Koala"},
{jp:"カンガルー",romaji:"Kangaruu",arti:"Kangguru"},
{jp:"ハムスター",romaji:"Hamusutaa",arti:"Hamster"},
{jp:"モルモット",romaji:"Morumotto",arti:"Marmut"},
{jp:"フェレット",romaji:"Feretto",arti:"Ferret"},
{jp:"アルパカ",romaji:"Arupaka",arti:"Alpaka"},
{jp:"ラマ",romaji:"Rama",arti:"Llama"},
{jp:"バイソン",romaji:"Baison",arti:"Bison"},
{jp:"オランウータン",romaji:"OranUutan",arti:"Orangutan"},
{jp:"チーター",romaji:"Chiitaa",arti:"Cheetah"},
{jp:"ジャガー",romaji:"Jagaa",arti:"Jaguar"},
{jp:"ヒョウ",romaji:"Hyou",arti:"Macan Tutul"},
{jp:"アザラシ",romaji:"Azarashi",arti:"Anjing Laut"},
{jp:"ペリカン",romaji:"Perikan",arti:"Pelikan"},
{jp:"フラミンゴ",romaji:"Furamingo",arti:"Flamingo"},
{jp:"シマウマ",romaji:"Shimauma",arti:"Zebra"},
{jp:"イノシシ",romaji:"Inoshishi",arti:"Babi Hutan"},
{jp:"ハリネズミ",romaji:"Harinezumi",arti:"Landak"},
{jp:"モグラ",romaji:"Mogura",arti:"Tahi Lalat"},
{jp:"カワウソ",romaji:"Kawauso",arti:"Berang-berang"},
{jp:"アライグマ",romaji:"Araiguma",arti:"Rakun"}

]

};