const makanan = {

id: "makanan",

nama: "Makanan",

data: [

{jp:"たべもの",romaji:"Tabemono",arti:"Makanan"},
{jp:"ごはん",romaji:"Gohan",arti:"Nasi"},
{jp:"パン",romaji:"Pan",arti:"Roti"},
{jp:"おにぎり",romaji:"Onigiri",arti:"Nasi Kepal"},
{jp:"すし",romaji:"Sushi",arti:"Sushi"},
{jp:"さしみ",romaji:"Sashimi",arti:"Sashimi"},
{jp:"ラーメン",romaji:"Raamen",arti:"Ramen"},
{jp:"うどん",romaji:"Udon",arti:"Udon"},
{jp:"そば",romaji:"Soba",arti:"Soba"},
{jp:"やきそば",romaji:"Yakisoba",arti:"Yakisoba"},
{jp:"てんぷら",romaji:"Tempura",arti:"Tempura"},
{jp:"とんかつ",romaji:"Tonkatsu",arti:"Tonkatsu"},
{jp:"からあげ",romaji:"Karaage",arti:"Ayam Goreng Jepang"},
{jp:"やきとり",romaji:"Yakitori",arti:"Sate Ayam Jepang"},
{jp:"ぎょうざ",romaji:"Gyouza",arti:"Gyoza"},
{jp:"たこやき",romaji:"Takoyaki",arti:"Takoyaki"},
{jp:"おこのみやき",romaji:"Okonomiyaki",arti:"Okonomiyaki"},
{jp:"カレー",romaji:"Karee",arti:"Kari"},
{jp:"オムライス",romaji:"Omuraisu",arti:"Nasi Omelet"},
{jp:"チャーハン",romaji:"Chaahan",arti:"Nasi Goreng"},
{jp:"やきめし",romaji:"Yakimeshi",arti:"Nasi Goreng Jepang"},
{jp:"べんとう",romaji:"Bentou",arti:"Bekal Makan"},
{jp:"みそしる",romaji:"Misoshiru",arti:"Sup Miso"},
{jp:"スープ",romaji:"Suupu",arti:"Sup"},
{jp:"サラダ",romaji:"Sarada",arti:"Salad"},
{jp:"たまご",romaji:"Tamago",arti:"Telur"},
{jp:"にく",romaji:"Niku",arti:"Daging"},
{jp:"ぎゅうにく",romaji:"Gyuuniku",arti:"Daging Sapi"},
{jp:"ぶたにく",romaji:"Butaniku",arti:"Daging Babi"},
{jp:"とりにく",romaji:"Toriniku",arti:"Daging Ayam"},
{jp:"さかな",romaji:"Sakana",arti:"Ikan"},
{jp:"えび",romaji:"Ebi",arti:"Udang"},
{jp:"かに",romaji:"Kani",arti:"Kepiting"},
{jp:"いか",romaji:"Ika",arti:"Cumi-cumi"},
{jp:"たこ",romaji:"Tako",arti:"Gurita"},
{jp:"まぐろ",romaji:"Maguro",arti:"Tuna"},
{jp:"さけ",romaji:"Sake",arti:"Salmon"},
{jp:"やさい",romaji:"Yasai",arti:"Sayuran"},
{jp:"くだもの",romaji:"Kudamono",arti:"Buah"},
{jp:"りんご",romaji:"Ringo",arti:"Apel"},
{jp:"みかん",romaji:"Mikan",arti:"Jeruk"},
{jp:"バナナ",romaji:"Banana",arti:"Pisang"},
{jp:"ぶどう",romaji:"Budou",arti:"Anggur"},
{jp:"いちご",romaji:"Ichigo",arti:"Stroberi"},
{jp:"メロン",romaji:"Meron",arti:"Melon"},
{jp:"すいか",romaji:"Suika",arti:"Semangka"},
{jp:"もも",romaji:"Momo",arti:"Persik"},
{jp:"なし",romaji:"Nashi",arti:"Pir"},
{jp:"パイナップル",romaji:"Painappuru",arti:"Nanas"},
{jp:"ケーキ",romaji:"Keeki",arti:"Kue"},
{jp:"アイスクリーム",romaji:"Aisukuriimu",arti:"Es Krim"},
{jp:"チョコレート",romaji:"Chokoreeto",arti:"Cokelat"},
{jp:"クッキー",romaji:"Kukkii",arti:"Kue Kering"},
{jp:"ビスケット",romaji:"Bisuketto",arti:"Biskuit"},
{jp:"キャンディー",romaji:"Kyandii",arti:"Permen"},
{jp:"もち",romaji:"Mochi",arti:"Mochi"},
{jp:"だんご",romaji:"Dango",arti:"Dango"},
{jp:"どらやき",romaji:"Dorayaki",arti:"Dorayaki"},
{jp:"あんぱん",romaji:"Anpan",arti:"Roti Kacang Merah"},
{jp:"コロッケ",romaji:"Korokke",arti:"Kroket Jepang"},
{jp:"ハンバーグ",romaji:"Hanbaagu",arti:"Hamburg Steak"},
{jp:"ハンバーガー",romaji:"Hanbaagaa",arti:"Hamburger"},
{jp:"ピザ",romaji:"Piza",arti:"Pizza"},
{jp:"スパゲッティ",romaji:"Supagetti",arti:"Spaghetti"},
{jp:"サンドイッチ",romaji:"Sandoicchi",arti:"Sandwich"},
{jp:"ホットドッグ",romaji:"Hottodoggu",arti:"Hot Dog"},
{jp:"フライドポテト",romaji:"FuraidoPoteto",arti:"Kentang Goreng"},
{jp:"ポテトチップス",romaji:"PotetoChippusu",arti:"Keripik Kentang"},
{jp:"チーズ",romaji:"Chiizu",arti:"Keju"},
{jp:"バター",romaji:"Bataa",arti:"Mentega"},
{jp:"ジャム",romaji:"Jamu",arti:"Selai"},
{jp:"ヨーグルト",romaji:"Yooguruto",arti:"Yogurt"},
{jp:"とうふ",romaji:"Toufu",arti:"Tahu"},
{jp:"なっとう",romaji:"Nattou",arti:"Natto"},
{jp:"キムチ",romaji:"Kimuchi",arti:"Kimchi"},
{jp:"カレーライス",romaji:"Kareeraisu",arti:"Nasi Kari"},
{jp:"チャーハン",romaji:"Chaahan",arti:"Nasi Goreng Jepang"},
{jp:"オムレツ",romaji:"Omuretsu",arti:"Omelet"},
{jp:"ゆでたまご",romaji:"Yudetamago",arti:"Telur Rebus"},
{jp:"めだまやき",romaji:"Medamayaki",arti:"Telur Mata Sapi"},
{jp:"ソーセージ",romaji:"Sooseeji",arti:"Sosis"},
{jp:"ベーコン",romaji:"Beekon",arti:"Bacon"},
{jp:"ハム",romaji:"Hamu",arti:"Ham"},
{jp:"シリアル",romaji:"Shiriaru",arti:"Sereal"},
{jp:"おかゆ",romaji:"Okayu",arti:"Bubur"},
{jp:"しお",romaji:"Shio",arti:"Garam"},
{jp:"さとう",romaji:"Satou",arti:"Gula"},
{jp:"しょうゆ",romaji:"Shouyu",arti:"Kecap Asin"},
{jp:"ソース",romaji:"Soosu",arti:"Saus"},
{jp:"ケチャップ",romaji:"Kechappu",arti:"Kecap Tomat"},
{jp:"マヨネーズ",romaji:"Mayoneezu",arti:"Mayones"},
{jp:"こしょう",romaji:"Koshou",arti:"Lada"},
{jp:"わさび",romaji:"Wasabi",arti:"Wasabi"},
{jp:"しょうが",romaji:"Shouga",arti:"Jahe"},
{jp:"にんにく",romaji:"Ninniku",arti:"Bawang Putih"},
{jp:"たまねぎ",romaji:"Tamanegi",arti:"Bawang Bombay"},
{jp:"ねぎ",romaji:"Negi",arti:"Daun Bawang"},
{jp:"きのこ",romaji:"Kinoko",arti:"Jamur"},
{jp:"のり",romaji:"Nori",arti:"Rumput Laut"},
{jp:"こんぶ",romaji:"Konbu",arti:"Rumput Laut Kombu"},
{jp:"ひじき",romaji:"Hijiki",arti:"Rumput Laut Hijiki"}

]

};