const sekolah = {

id: "sekolah",

nama: "Sekolah",

data: [

{jp:"がっこう",romaji:"Gakkou",arti:"Sekolah"},
{jp:"きょうしつ",romaji:"Kyoushitsu",arti:"Ruang Kelas"},
{jp:"こうちょう",romaji:"Kouchou",arti:"Kepala Sekolah"},
{jp:"せんせい",romaji:"Sensei",arti:"Guru"},
{jp:"がくせい",romaji:"Gakusei",arti:"Siswa"},
{jp:"せいと",romaji:"Seito",arti:"Murid"},
{jp:"ともだち",romaji:"Tomodachi",arti:"Teman"},
{jp:"つくえ",romaji:"Tsukue",arti:"Meja"},
{jp:"いす",romaji:"Isu",arti:"Kursi"},
{jp:"ほん",romaji:"Hon",arti:"Buku"},
{jp:"きょうかしょ",romaji:"Kyoukasho",arti:"Buku Pelajaran"},
{jp:"ノート",romaji:"Nooto",arti:"Buku Tulis"},
{jp:"えんぴつ",romaji:"Enpitsu",arti:"Pensil"},
{jp:"ボールペン",romaji:"Boorupen",arti:"Pulpen"},
{jp:"けしゴム",romaji:"Keshigomu",arti:"Penghapus"},
{jp:"ものさし",romaji:"Monosashi",arti:"Penggaris"},
{jp:"はさみ",romaji:"Hasami",arti:"Gunting"},
{jp:"のり",romaji:"Nori",arti:"Lem"},
{jp:"かばん",romaji:"Kaban",arti:"Tas"},
{jp:"ランドセル",romaji:"Randoseru",arti:"Tas Sekolah Jepang"},
{jp:"こくばん",romaji:"Kokuban",arti:"Papan Tulis"},
{jp:"チョーク",romaji:"Chooku",arti:"Kapur"},
{jp:"ホワイトボード",romaji:"Howaitoboodo",arti:"Papan Tulis Putih"},
{jp:"マーカー",romaji:"Maakaa",arti:"Spidol"},
{jp:"じゅぎょう",romaji:"Jugyou",arti:"Pelajaran"},
{jp:"しゅくだい",romaji:"Shukudai",arti:"Pekerjaan Rumah"},
{jp:"しけん",romaji:"Shiken",arti:"Ujian"},
{jp:"テスト",romaji:"Tesuto",arti:"Tes"},
{jp:"せいせき",romaji:"Seiseki",arti:"Nilai"},
{jp:"べんきょう",romaji:"Benkyou",arti:"Belajar"},
{jp:"れんしゅう",romaji:"Renshuu",arti:"Latihan"},
{jp:"こたえ",romaji:"Kotae",arti:"Jawaban"},
{jp:"しつもん",romaji:"Shitsumon",arti:"Pertanyaan"},
{jp:"へんじ",romaji:"Henji",arti:"Jawaban Balasan"},
{jp:"じしょ",romaji:"Jisho",arti:"Kamus"},
{jp:"えいご",romaji:"Eigo",arti:"Bahasa Inggris"},
{jp:"にほんご",romaji:"Nihongo",arti:"Bahasa Jepang"},
{jp:"すうがく",romaji:"Suugaku",arti:"Matematika"},
{jp:"りか",romaji:"Rika",arti:"IPA"},
{jp:"しゃかい",romaji:"Shakai",arti:"IPS"},
{jp:"おんがく",romaji:"Ongaku",arti:"Musik"},
{jp:"びじゅつ",romaji:"Bijutsu",arti:"Seni"},
{jp:"たいいく",romaji:"Taiiku",arti:"Olahraga"},
{jp:"れきし",romaji:"Rekishi",arti:"Sejarah"},
{jp:"ちり",romaji:"Chiri",arti:"Geografi"},
{jp:"かがく",romaji:"Kagaku",arti:"Sains"},
{jp:"パソコン",romaji:"Pasokon",arti:"Komputer"},
{jp:"インターネット",romaji:"Intaanetto",arti:"Internet"},
{jp:"としょかん",romaji:"Toshokan",arti:"Perpustakaan"},
{jp:"こうてい",romaji:"Koutei",arti:"Halaman Sekolah"},
{jp:"たいいくかん",romaji:"Taiikukan",arti:"Gedung Olahraga"},
{jp:"しょくどう",romaji:"Shokudou",arti:"Kantin"},
{jp:"きゅうしょく",romaji:"Kyuushoku",arti:"Makan Siang Sekolah"},
{jp:"じかんわり",romaji:"Jikanwari",arti:"Jadwal Pelajaran"},
{jp:"チャイム",romaji:"Chaimu",arti:"Bel Sekolah"},
{jp:"せき",romaji:"Seki",arti:"Tempat Duduk"},
{jp:"しゅっせき",romaji:"Shusseki",arti:"Kehadiran"},
{jp:"けっせき",romaji:"Kesseki",arti:"Tidak Hadir"},
{jp:"そつぎょう",romaji:"Sotsugyou",arti:"Kelulusan"},
{jp:"にゅうがく",romaji:"Nyuugaku",arti:"Masuk Sekolah"},
{jp:"ぶかつ",romaji:"Bukatsu",arti:"Klub Sekolah"}

]

};