const tubuh = {

id:"tubuh",

nama:"Anggota Tubuh",

data:[

{jp:"からだ",romaji:"Karada",arti:"Tubuh"},
{jp:"あたま",romaji:"Atama",arti:"Kepala"},
{jp:"かお",romaji:"Kao",arti:"Wajah"},
{jp:"かみ",romaji:"Kami",arti:"Rambut"},
{jp:"ひたい",romaji:"Hitai",arti:"Dahi"},
{jp:"まゆげ",romaji:"Mayuge",arti:"Alis"},
{jp:"まつげ",romaji:"Matsuge",arti:"Bulu Mata"},
{jp:"め",romaji:"Me",arti:"Mata"},
{jp:"ひとみ",romaji:"Hitomi",arti:"Pupil"},
{jp:"みみ",romaji:"Mimi",arti:"Telinga"},
{jp:"はな",romaji:"Hana",arti:"Hidung"},
{jp:"くち",romaji:"Kuchi",arti:"Mulut"},
{jp:"くちびる",romaji:"Kuchibiru",arti:"Bibir"},
{jp:"は",romaji:"Ha",arti:"Gigi"},
{jp:"した",romaji:"Shita",arti:"Lidah"},
{jp:"あご",romaji:"Ago",arti:"Dagu"},
{jp:"ほほ",romaji:"Hoho",arti:"Pipi"},
{jp:"くび",romaji:"Kubi",arti:"Leher"},
{jp:"かた",romaji:"Kata",arti:"Bahu"},
{jp:"うで",romaji:"Ude",arti:"Lengan"},
{jp:"ひじ",romaji:"Hiji",arti:"Siku"},
{jp:"て",romaji:"Te",arti:"Tangan"},
{jp:"てのひら",romaji:"Te no Hira",arti:"Telapak Tangan"},
{jp:"ゆび",romaji:"Yubi",arti:"Jari"},
{jp:"おやゆび",romaji:"Oyayubi",arti:"Ibu Jari"},
{jp:"ひとさしゆび",romaji:"Hitosashiyubi",arti:"Jari Telunjuk"},
{jp:"なかゆび",romaji:"Nakayubi",arti:"Jari Tengah"},
{jp:"くすりゆび",romaji:"Kusuriyubi",arti:"Jari Manis"},
{jp:"こゆび",romaji:"Koyubi",arti:"Jari Kelingking"},
{jp:"つめ",romaji:"Tsume",arti:"Kuku"},
{jp:"むね",romaji:"Mune",arti:"Dada"},
{jp:"せなか",romaji:"Senaka",arti:"Punggung"},
{jp:"おなか",romaji:"Onaka",arti:"Perut"},
{jp:"こし",romaji:"Koshi",arti:"Pinggang"},
{jp:"おしり",romaji:"Oshiri",arti:"Bokong"},
{jp:"あし",romaji:"Ashi",arti:"Kaki"},
{jp:"もも",romaji:"Momo",arti:"Paha"},
{jp:"ひざ",romaji:"Hiza",arti:"Lutut"},
{jp:"すね",romaji:"Sune",arti:"Tulang Kering"},
{jp:"ふくらはぎ",romaji:"Fukurahagi",arti:"Betis"},
{jp:"あしくび",romaji:"Ashikubi",arti:"Pergelangan Kaki"},
{jp:"かかと",romaji:"Kakato",arti:"Tumit"},
{jp:"あしのうら",romaji:"Ashi no Ura",arti:"Telapak Kaki"},
{jp:"あしのゆび",romaji:"Ashi no Yubi",arti:"Jari Kaki"},
{jp:"ほね",romaji:"Hone",arti:"Tulang"},
{jp:"きんにく",romaji:"Kinniku",arti:"Otot"},
{jp:"ち",romaji:"Chi",arti:"Darah"},
{jp:"しんぞう",romaji:"Shinzou",arti:"Jantung"},
{jp:"はい",romaji:"Hai",arti:"Paru-paru"},
{jp:"い",romaji:"I",arti:"Lambung"},
{jp:"かんぞう",romaji:"Kanzou",arti:"Hati"},
{jp:"じんぞう",romaji:"Jinzou",arti:"Ginjal"},
{jp:"のう",romaji:"Nou",arti:"Otak"},
{jp:"ひふ",romaji:"Hifu",arti:"Kulit"},
{jp:"せ",romaji:"Se",arti:"Punggung Atas"},
{jp:"わき",romaji:"Waki",arti:"Ketiak"},
{jp:"のど",romaji:"Nodo",arti:"Tenggorokan"},
{jp:"こえ",romaji:"Koe",arti:"Suara"},
{jp:"なみだ",romaji:"Namida",arti:"Air Mata"},
{jp:"あせ",romaji:"Ase",arti:"Keringat"},
{jp:"えがお",romaji:"Egao",arti:"Senyuman"}

]

};